// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDm6TDIi3pmhI4rla7BPpsHLhQ2WTCuuc',
    appId: '1:657549718965:web:3d52013a632b0f02f0d5fc',
    messagingSenderId: '657549718965',
    projectId: 'my-app-294bf',
    authDomain: 'my-app-294bf.firebaseapp.com',
    storageBucket: 'my-app-294bf.appspot.com',
    measurementId: 'G-WK74THQ7QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD60_N3BTacPxfy-wS8SEpfArRxA23c7yk',
    appId: '1:657549718965:android:cdc625a2c6e87158f0d5fc',
    messagingSenderId: '657549718965',
    projectId: 'my-app-294bf',
    storageBucket: 'my-app-294bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpSMdmvfrPnNrOkp99Nys5wPvCgG673pk',
    appId: '1:657549718965:ios:a5e59b1a2bc4bac6f0d5fc',
    messagingSenderId: '657549718965',
    projectId: 'my-app-294bf',
    storageBucket: 'my-app-294bf.appspot.com',
    iosBundleId: 'com.example.foodplanets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpSMdmvfrPnNrOkp99Nys5wPvCgG673pk',
    appId: '1:657549718965:ios:a5e59b1a2bc4bac6f0d5fc',
    messagingSenderId: '657549718965',
    projectId: 'my-app-294bf',
    storageBucket: 'my-app-294bf.appspot.com',
    iosBundleId: 'com.example.foodplanets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDm6TDIi3pmhI4rla7BPpsHLhQ2WTCuuc',
    appId: '1:657549718965:web:6e2944db24b2564bf0d5fc',
    messagingSenderId: '657549718965',
    projectId: 'my-app-294bf',
    authDomain: 'my-app-294bf.firebaseapp.com',
    storageBucket: 'my-app-294bf.appspot.com',
    measurementId: 'G-E02FK07MKG',
  );
}
